raspberrypi/rpicam-apps

CMakeLists.txt
circular_output.cpp
egl_preview.cpp
jpeg.cpp
libcamera_app.hpp
libcamera_still.cpp
libcamera_vid.cpp
mjpeg_encoder.cpp
mjpeg_encoder.hpp

Fix some findings while preparing a buildroot libcamera-apps package:
- cmake: remove unsafe host include path for libdrm (use pkgconfig instead)
- cmake: remove unrecognized gcc command-line option
- libcamera_vid: fix getline call (needs size_t)
- libcamera_still: fix getline call (needs size_t)
- libcamera_app: fix int64_t constants
- cmake: fix linking with exif, jpeg
- cmake: add install target
- cmake: no need to link against ipa_rpi.so

fix buildroot crosscompile

---

options.hpp

The option parser sets a default value of 0 for "gain" and "analoggain"
if not provided.  Since they both reference the same underlying variable,
if "analoggain" is set in the command line, the variable would be rest to
the default (0) since "gain" is lower in the option list.

Fix option parser to use "analoggain" correctly.

---

libcamera_app.hpp
libcamera_encoder.hpp
libcamera_hello.cpp
libcamera_jpeg.cpp
libcamera_raw.cpp
libcamera_still.cpp
libcamera_vid.cpp

@naushir
Here's that re-work of the buffer and metadata passing that we were talking about. Needless to say, the original plan bit the dust almost immediately on contact with reality - I found I was making quite a lot of use of ControlLists, and didn't really want to rewrite that. The aim was never really to produce de-libcamera-ified apps, so I backed off a bit. Instead I have:
1. Renamed the RequestCompletePayload object as a BufferMetadataSet. Not sure I love this name either, but it's not as bad. Still open to other suggestions, though!
2. I've added the instantaneous framerate to the BufferMetadataSet, and it gets calculated in the requestComplete callback.
3. Now we pass BufferMetadataSets round everywhere, rather than BufferMaps. This way, the metadata ControlList and the framerate …

Buffer and metadata rework

---

circular_output.cpp
h264_encoder.cpp
libcamera_still.cpp
libcamera_vid.cpp
output.cpp

- Unused return value from getline().
- printf format specifiers for 64-bit integers.
- Warning about narrowing conversion from int to bool.

Fix some compiler warning.

---

drm_preview.cpp

It will fail later anyway, so it's more helpful to raise a specific
error immediately.

Make DRM preview fail earlier if we are not DRM master

---

CMakeLists.txt

Raspberry Pi OS 64-bit gcc objects to -mfpu=neon-fp-armv8 (the
presence of Neon is implicit on 64-bit platforms).

Fix build for 64-bit OS users

---

libcamera_raw.cpp

It serves no purpose here, and might slow up the framerate.

libcamera-raw: Force colour denoise off

---

libcamera_app.hpp

The number of raw buffers must be set up to match the number of output
buffers, unconditionally. libcamera_app.hpp requires all streams that
will feature in the same requests to have the same number of buffers
available.

libcamera-raw: Fix video capture with full res raw images

---

mjpeg_encoder.cpp
test.py

Fixing up some type warnings had caused the jpeg length not to be
returned correctly from the encodeJPEG method.
Test script has also been altered to spot this.
Fixes: b20dc097621a ("fix buildroot crosscompile (#1)")

mjpeg_encoder: fix bug that truncated jpegs to 4096 bytes

---

libcamera_encoder.hpp

There was a case where two mutexes were acquired in different orders
causing a deadlock.

Fix deadlock in H.264 encoder

---

encoder.hpp
h264_encoder.cpp
h264_encoder.hpp
libcamera_encoder.hpp
mjpeg_encoder.cpp
mjpeg_encoder.hpp
null_encoder.cpp
null_encoder.hpp

Previously LibcameraEncoder::EncodeBuffer used to return a handle
that would in theory allow an encoder to return buffers out-of-order
(though LibcameraEncoder::encodeBufferDone never handled this). This
entangles the LibcameraEncoder and the Encoder together more than is
necessary.
Instead, use the memory pointer, which we already have, as the
handle. This will make it easier to handle out-of-order completion,
should we choose to do so in future.

Make interface from libcameraApp to Encoder cleaner

---

libcamera_app.hpp
mjpeg_encoder.cpp
mjpeg_encoder.hpp

@naushir Some modest improvements to mjpeg throughput.
I've changed the way the multiple threads in the mjpeg encoder work slightly. I think this arrangement is marginally better and is probably a better template to copy in future work.
And I've upped the buffer count for video to 6. It does result in fewer frame drops when working mjpeg quite hard. Note the mjpeg throughput is somewhat sensitive to both the preview window and colour denoise!

Mjpeg improvements

---

libcamera_app.hpp

Reference [Issue 36](https://github.com/raspberrypi/libcamera-apps/issues/36), turned out it was a fairly simple change.
The project now builds, and libcamera-hello works, but nothing else is tested on this PR.

Change FrameDurations to FrameDurationLimits

---

frame_info.hpp

@naushir Just a fix for a small copy-paste error. It bit me when I tried running a sensor without the AWB!

Fix typo in FrameInfo which caused crash when no ColourGains present

---

h264_encoder.cpp

Given that we are using dmabufs, these fields do not seem to be necessary to
fill in the format structure.

encoder: Do not explicitly set buffer size and bytesperline in format struct

---

CMakeLists.txt

libcamera is now the "libcamera" (rather than just "camera") package,
and has also had a "base" library split out which we must now link.

Build fixups for latest libcamera version

---

CMakeLists.txt

Only apply Pi 3/4 specific optimisations if explicitly reuested to do
so on the command line. This ensures that by default (in 32-bit
Raspberry Pi OS distributions) the executables will work on all
devices.

Build 32-bit binaries by default that run on all Pis.

---

checkstyle.py

Use the original authorship licence of the checkstyle.py script file. It was
erroneously set to the default of "BSD-2-Clause" for this repository.

checkstyle: Update license to "GPL-2.0-or-later" for the script

---

.clang-format

The Pi repos are not yet shipping with a version of clang-format that
supports c++17, so this parameter causes commits to fail if you are
doing them directly from the Pi.
For the time being little is lost by omitting it, and we can replace
it once the repositories have moved on.

Remove c++17 reference from .clang-format

---

CMakeLists.txt
core/options.hpp

This define switches us to large files on 32 bit systems, and is
harmless on 64 bit systems (where large files are the default).

Support files larger than 2GB

---

core/CMakeLists.txt

It's a bit strange why this did not fail all the time.
I suspect the "wrong" variable may have been cached by cmake, so it kept working when it should not have been!

build: Fix error linking to libcamera-base.so

---

post_processing_stages/negate_stage.cpp

The loop can be better optimised when the vectorising compiler cannot
be used.

post-processing: negate: optimise for non-vectorising builds

---

core/libcamera_app.cpp
core/libcamera_app.hpp
core/options.hpp
post_processing_stages/face_detect_cv_stage.cpp

@naushir @RaspiShonak
There are 3 commits here:
- The first replaces the individual stream pointers in the app by a map (Naush suggested this a little while back, I think).
- The second adds a "lo res" stream to the viewfinder and video use cases.
- The final commit amends the face detect stage to use the low resolution stream so as to avoid the resize, but you do have to add something like `--lores-width 640 --lores-height 480` to the command line.

Lores stream

---

CMakeLists.txt
core/CMakeLists.txt
core/post_processing_stage.cpp

A small tweak is required in post_processing_stage.cpp to ensure the
"stages" table is initialised before anyone tries to put anything in
it.

build: Use shared rather than static libraries

---

core/libcamera_app.cpp
preview/drm_preview.cpp
preview/egl_preview.cpp
preview/null_preview.cpp
preview/preview.hpp

Some devices can only render limited size images into the preview
window (for Pi 3, this limit is 2048x2048). We now fetch these limits,
and ensure that the viewfinder mode doesn't request anything larger
from the camera/ISP.

Limit viewfinder image size by the preview window capabilities

---

post_processing_stages/CMakeLists.txt
post_processing_stages/motion_detect.json
post_processing_stages/motion_detect_stage.cpp

The motion_detect stage looks for pixel differences in the low
resolution image, which should normally be configured quite small,
such as 128x96 pixels. If enough pixels have changed sufficiently,
this counts as "motion".

post-processing: Add a motion_detect stage

---

apps/libcamera_still.cpp
core/still_options.hpp

The "immediate" option causes libcamera-still to capture the very
first frame from the camera, with no initial preview phase at all.

libcamera-still: Add option for immediate capture

---

core/post_processing_stage.hpp

Two small fix-ups to prevent one failure and some Boost warnings when
building with GCC 10.3.0. Harmless with earlier versions.

build: fix compiler error and warnings with GCC 10

---

image/dng.cpp

Versions of libtiff from 4.2.0 onwards have made a non-backwards
compatible API change. Unfortunately code that was correct previously
still compiles but crashes the application at runtime.

dng: Work around non-backwards compatible change to libtiff

---

core/completed_request.hpp
core/libcamera_app.cpp
core/libcamera_app.hpp
core/metadata.hpp

Mark CompletedRequest as non-movable.
Fixup Metadata::Set() forwarding the metadata value correctly.

libcamera_app: Consolidate move operations

---

core/libcamera_app.cpp

It wasn't checking that the raw stream existed before accessing it.

core: Fix unsafe memory access in ConfigureStill

---

.github/workflows/libcamera-apps-test.yml
test.py

Runs a small selection of post-processing tests. Warnings are printed
if OpenCV, TFLite or the model used by TFLite are not found, but the
tests are not marked as failures.

test: Add post-processing tests

---

CMakeLists.txt

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

Do not override CXXFLAGS from external build system

---

CMakeLists.txt
core/CMakeLists.txt
core/version.cmake
package.cmake

The new make target "package_source" will now save the upstream git commit SHA
into a file that is saved in the source tarball generated.  This SHA will then
be used by the version.py script when building from the tarball, and preserving
the upstream SHA versioning.
This removes the usage of the -DVERSION_SHA=... command line argument.
As a drive-by change, rename the -auto flag to -intree.

build: Add cpack support for src/bin distribution

---

apps/libcamera_detect.cpp
apps/libcamera_hello.cpp
apps/libcamera_jpeg.cpp
apps/libcamera_raw.cpp
apps/libcamera_still.cpp
apps/libcamera_vid.cpp
core/completed_request.hpp
core/libcamera_app.cpp
core/libcamera_app.hpp
core/libcamera_encoder.hpp
core/post_processor.cpp
core/post_processor.hpp
post_processing_stages/annotate_cv_stage.cpp
post_processing_stages/face_detect_cv_stage.cpp
post_processing_stages/hdr_stage.cpp
post_processing_stages/motion_detect_stage.cpp
post_processing_stages/negate_stage.cpp
post_processing_stages/object_classify_tf_stage.cpp
post_processing_stages/object_detect_draw_cv_stage.cpp
post_processing_stages/object_detect_tf_stage.cpp
post_processing_stages/plot_pose_cv_stage.cpp
post_processing_stages/pose_estimation_tf_stage.cpp
post_processing_stages/post_processing_stage.hpp
post_processing_stages/segmentation_tf_stage.cpp
post_processing_stages/sobel_cv_stage.cpp
post_processing_stages/tf_stage.cpp
post_processing_stages/tf_stage.hpp

Unfortunately this is one big all-or-nothing change. There's a lot of
mundane CompletedRequest -> CompletedRequestPtr changes here, but some
are more significant.
* The shared_ptr has a custom deleter so that once all references to
it are dropped it calls LibcameraApp::queueRequest for
recycling. (There's a nasty corner case about a CompletedRequest
being recycled once the camera has been stopped and restarted.)
* LibcameraApp::ShowPreview needs to take a reference to the shared_ptr.
* LibcameraEncoder::EncodeBuffer needs to take a reference to the
shared_ptr.
* The post-processor can re-use the shared_ptr both when it receives
the CompletedRequest, and when it gets passed on to the message
queue for the application.
* Neither the encoder nor the preview need a callback anymore to pass …

Use shared_ptr to pass CompletedRequests around

---

encoder/mjpeg_encoder.cpp
image/jpeg.cpp

Some slight tidying, and in particular we don't actually need to copy
any pixels beyond the last full block of 16 rows, we can just re-use
pointers to the last row.

jpeg, mjpeg: Minor improvements to encoding

---

apps/libcamera_still.cpp

The intended behaviour is that you can do one capture after
another. The mechanism for quitting is unchanged (x+Enter or USR2).

libcamera-still: In keypress/signal mode return to preview after capture

---

core/still_options.hpp
image/jpeg.cpp

Use "--thumb none" to avoid creating and saving a thumbanil image.
Sigend-off-by: David Plowman <david.plowman@raspberrypi.com>

image: Allow JPEGs to be saved without a thumbnail

---

core/video_options.hpp
output/circular_output.cpp
output/circular_output.hpp

The buffer can now be > 4GB. The buffer size can also be specified on
the command line with the --circular option.

output: Upgrade circular buffer output for 64-bit systems

---

apps/libcamera_still.cpp

The "wrap" option for the filename counter had not been implemented
for libcamera-still.

libcamera-still: Implement wrap feature

---

core/options.hpp
core/still_options.hpp
core/video_options.hpp

clang-format does not like this type of formatting, so keep the checkstyle
script from complaining on these blocks.

options: Do not run clang format on the options structures.

---

core/libcamera_app.cpp
core/libcamera_encoder.hpp

The following libcamera API change breaks the libcamera-apps builds:
commit 560f5cf998646ddc54a20dc1c7326012834d3204
Author: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Date:   Mon Nov 29 20:38:10 2021 +0200
libcamera: base: shared_fd: Rename fd() to get()
For consistency with UniqueFD, rename the fd() function to get().
Renaming UniqueFD::get() to fd() would have been another option, but was
rejected to keep as close as possible to the std::shared_ptr<> and
std::unique_ptr<> APIs.
Signed-off-by: Laurent Pinchart <laurent.pinchart@ideasonboard.com>
Reviewed-by: Jacopo Mondi <jacopo@jmondi.org>
Reviewed-by: Hirokazu Honda <hiroh@chromium.org>
Fix the breakage by using plane.fd.get() instead of plane.fd.fd().

core: Fix build breakage after libcamera API changes.

---

encoder/h264_encoder.cpp
encoder/h264_encoder.hpp

This means you can close and open the h264 encoder multiple times
without eventually running out of CMA.

h264: Tidy up the encoder properly when it shuts

---

output/circular_output.cpp

Can be tested with: 
```
libcamera-vid --circular 1000 --frames 60 --framerate 30 --width 1920 --height 1080 --codec yuv420 -o - \
| pv -r > /dev/null
```
And allows for piping to FFmpeg/Gstreamer, with the purpose of holding the encode until all frames have been captured (up to the amount that can fit in circular ram buffer):
```
libcamera-vid --circular 1000 --frames 60 --framerate 30 --width 1920 --height 1080 --codec yuv420 -o - \
| ffmpeg -y -f rawvideo -pix_fmt yuv420p -s:v 1920x1080 -r 30 -i - -c:v h264_v4l2m2m -b:v 25M ~/out.mp4
```

Allow circular output to write to stdout

---

core/libcamera_app.cpp
core/libcamera_app.hpp

This means it can't access buffers that are being deallocated when the
display is very laggy (such as when using VNC). Correspondingly, the
preview thread is started at the end of the Configure methods.

core: Stop preview thread in Teardown method

---

preview/egl_preview.cpp

This time it's because X11 #defines "None" (which is going to be a
problem when the libcamera colour space changes get merged). This
workaround seems to be adequate.

preview: Fix more build headaches caused by X11

---

output/net_output.cpp

Without SO_REUSEADDR listening sockets cannot be re-opened within 2 minutes, this just enables the option so you can restart a listening app without delay.

Added so_reuseaddr to listening sockets so they can be restarted.

---

apps/libcamera_vid.cpp

This copies a previous fix in libcamera-still (fa95bcb), which applies
here too.

libcamera-vid: Signals were not being "cancelled" in signal mode

---

core/libcamera_app.cpp
preview/egl_preview.cpp

A preview fix (9d89e1e) actually broke this. There was a particularly
subtle issue with EGL where it was still only obeying the previous
preview thread which has stopped running.

preview: Preview was not resuming properly during timelapse

---

core/options.cpp

The exposure options did not include this, so it has been added.

options: Support "long" exposure mode

---

utils/camera-bug-report

Without this argument, we do not know what to run.

utils: Require the -c argument for camera-bug-report

---

core/libcamera_app.cpp

preview_item_ is effectively a 1-deep queue of frames still to
display. It's best to clear this when the preview is stopped so that
there's no way that anyone might attempt to display it if the preview
restarts (by which time it would be stale).

preview: Clear the preview item queue when we stop the preview

---

core/frame_info.hpp

Fix for clang fatal error: implicit instantiation of undefined template 'std::basic_stringstream<char>'

Include sstream header

---

core/libcamera_app.cpp

Previously if the camera failed to start, but the post processor was
already started, StopCamera() would have failed to clean up the post
processor properly. There's no harm in starting it after, the
requestComplete() callback can't be invoked before it's connected.

post_processor: Only start it once the camera is successfully started

---

README.md
apps/libcamera_vid.cpp

Since build instructions are maintained within another doc that is linked to, highlighted by added subtitle "Build" so reader in text mode sees that another document should be referenced.

Isolated build instructions so link is more prominent in a text mode

---

output/circular_output.hpp

It was returning -1 (as a size_t) when wrptr_ == rptr_ (the buffer is
empty).

Fix CircularOutput::Available() underflow on an empty buffer

---

core/libcamera_app.cpp
core/libcamera_encoder.hpp

Framebuffer timestamps account for SW overheads and pipelining, so might be a
bit glitchy.

Use controls::SensorTimestamp for timestamps if possible.

---

post_processing_stages/annotate_cv_stage.cpp

raspivid used to do this, so we should too.

annotate_cv_stage: Allow date/time format directives (as per strftime)

---

preview/drm_preview.cpp

"bo_handles" need to be closed, and although I can't find a "regular"
API call there does appear to be a DRM ioctl that does this.

previews: Fix memory leak in DRM preview

---

apps/libcamera_still.cpp

These command line arguments set together would not do the expected thing.
Fix this by having a wait loop after configuring stills mode and wait for the
signal/keypress before taking the capture.

libcamera-still: Allow --immediate and keypress/signal to work together

---

image/jpeg.cpp

Exif has a variety of date tags, with slightly different
meanings. This commit adds a couple more just in case anyone is
expecting them.

image: Add more of the exif date tags

---

core/libcamera_app.cpp

This is not a real problem, but the compiler cannot understand that we are using
the deleted pointer as a lookup.  So move the lookup to above the delete
statement.

core: Fix compiler warning about use after delete

---

encoder/libav_encoder.cpp

This stops a possible compiler warning. Sadly avformat_open_input needs a
non-const value, so input_fmt cannot be a const.

libav: Cast out of const for av_find_input_format()

---

encoder/libav_encoder.cpp
encoder/libav_encoder.hpp

Hey folks, ran into a compile error building this against ffmpeg 5.0 - the compiler really wanted the input_fmt to be const.

Add const to input_fmt

---

encoder/h264_encoder.cpp

Set the user requested framerate through VIDIOC_S_PARM so that it is set in the
SPS section of the encoded stream.

h264_encoder: Set framerate on the kernel driver

---

image/jpeg.cpp

The existing string of "libcamera-still" was not appropriate when using the
libcamera-jpeg application.

jpeg: Set the exif application tag to libcamera-apps

---

core/libcamera_app.cpp

libcamera commt 09c1b081baa2 (libcamera: controls: Generate and use fixed-sized Span types)
break the existing Span API.  Fix this.

core: Fix libcamera::Span API breakage

---

apps/CMakeLists.txt
apps/libcamera_raw.cpp
apps/libcamera_still.cpp
apps/libcamera_vid.cpp
core/libcamera_encoder.hpp
core/options.cpp
core/options.hpp
core/still_options.hpp
output/output.cpp
output/output.hpp
utils/test.py

These are William's commits that add metadata output for video streams, plus a couple more commits to add the same metadata formatting options to stills capture, and also to add some tests.
Things ended up a bit awkward because we wanted to get the Output objects to write the metadata, rather than hold up any other threads, but things are sufficiently compartmentalised that getting the metadata down there was slightly annoying. We've gone with copying the metadata into a queue in the output object, though an alternative would have been to hold on to a reference to the CompletedRequest instead.
On balance I think copying the metadata is OK - it only does it when it really has been requested, and holding onto the CompletedRequest might delay recycling the request back to libcamera which …

William's metadata output for video

---

apps/libcamera_detect.cpp
apps/libcamera_hello.cpp
apps/libcamera_jpeg.cpp
apps/libcamera_raw.cpp
apps/libcamera_still.cpp
apps/libcamera_vid.cpp
core/libcamera_app.cpp
core/libcamera_app.hpp

Handle possible hardware timeout error conditions by doing a StopCamera() and subsequent StartCamera() to restart the sensor.

apps: Handle sensor timeouts

---

core/libcamera_app.cpp

Starting and stopping the preview window actually causes a camera request object to leak, and will ultimately lead to libcamera stalling. Not a use case we've ever considered before, but we may as well make it work!

core: Fix a leaking request when preview windows are closed

---

encoder/libav_encoder.cpp

Replace the stdout filename "-" with "pipe:" when using libav.

libav: Correctly pipe to stdout

---

apps/libcamera_vid.cpp

Add a SIGINT handler to trap Ctrl+C to cleanly shut down the application.
This is needed for mkv and mp4 conainers that need to be finalised correctly
by libav.

libcamera-vid: Add SIGINT handler

---

core/video_options.hpp
encoder/libav_encoder.cpp

Add a new command line arguement (--audio-source) to allow the user to
select between an alsa or pulseaudio source device.

libav: Add option to choose the audio source (alsa/pulseaudio)

---

image/yuv.cpp

The other save modes have the option of setting a '-' path to redirect to stdout the YUV does not.
This normalizes the behavior

Add YUV save to stdout on "-" path

---

core/libcamera_app.cpp
core/libcamera_app.hpp

This allows new controls to be added to the stored list rather than replacing it. As before, the argument is invalidated.

core: LibcameraApp::SetControls has a "merge" option, true by default

---

apps/libcamera_still.cpp
core/libcamera_app.cpp
core/options.cpp
core/options.hpp
core/still_options.hpp

Added the ``--lens-position`` option, based on PR #411 but made optional and with the additional option to use the camera's default value. (The help text is deliberately vague about the units of measurement.)
Added AfTrigger, inferred when AfMode is Auto, but not for stills mode (to avoid moving the lens during capture).
The second commit modifies ``libcamera-still`` to trigger AF and wait for it to complete before capturing each image; the initial viewfinder session is forced to AfModeManual and therefore supports a LensPosition setting.
Frankly, this all seems a bit overwrought and I do wonder if it could be simpler?

More autofocus controls

---

encoder/null_encoder.cpp

This would cause a pop from the metadata queue in the output callback before the input callback has a chance to push to the queue.

output: null_encoder: Fix bug in ordering of input/output callbacks

---

core/libcamera_app.cpp
core/options.cpp
core/options.hpp
core/still_options.hpp

AF Mode now defaults to the highest supported mode (typically CAF) unless an explicit lens position or af_on_capture was requested. Speed and Range now default to "normal" rather than unset.

core: Tweak default AF options; AfMode now defaults typically to CAF

---

core/options.cpp

This fixes a null-pointer access when FrameDurationLimits is not available. In this case, the framerate is set to an invalid NAN.

options: prevent null pointer access to FrameDurationLimits

---

.github/workflows/libcamera-apps-style-checker.yml
.github/workflows/libcamera-apps-test.yml
.github/workflows/libcamera-test.yml

The v2 checkout/upload-artifact/download-artifact scripts are now deprecated,
switch to the v3 versions.

actions: Switch to v3 scripts

---

.github/workflows/libcamera-apps-test.yml
.github/workflows/libcamera-test.yml

Add imx708 to the camera matrix for all Github action scripts.

actions: Add imx708 tests

---

core/video_options.hpp

If the macroblocks/s exceed 245760, override the level option to "4.2".

options: Automatically set H.264 level 4.2 if needed

---

image/dng.cpp
image/jpeg.cpp

This is the only bit of AF metadata that seems to match a standard Exif tag. [XXX Because of numerical/API differences, the JPEG and DNG versions can encode slightly different values.]

image: Add Subject Distance to EXIF data, to encode Lens Position

---

core/options.cpp
preview/null_preview.cpp

This will only work if --info-text is explicitly provided in a command
line argument and not defaulted, and --nopreview has been set.

core: Allow info-text to display on the console

---

core/libcamera_app.cpp

VIDIOC_QUARYCAP is an unsigned long and should be passed as one.
Get rid of the following error:
core/libcamera_app.cpp:33:22: error: overflow in conversion from 'long unsigned int' to 'int' changes value from '2154321408' to '-2140645888' [-Werror=overflow]
33 |  int ret = ioctl(fd, VIDIOC_QUERYCAP, &caps);
Signed-off-by: Marcus Folkesson <marcus.folkesson@gmail.com>

core: pass VIDIOC_QUERYCAP as unsigned long

---

preview/qt_preview.cpp

Fix for #447.
The fix is required because QImage always pads each scanline to align to a 4-byte boundary. The simplest way to cope with this is to just call `QImage::scanLine(y)` for each line of output.
This is a simpler case than in Picamera2, as we do a conversion into the image rather than creating it with existing data -- no need to re-pack data in memory or make any advance assumptions about QImage alignment.

preview: Fix QtPreview for preview width not a multiple of 4

---

apps/libcamera_detect.cpp
apps/libcamera_jpeg.cpp
apps/libcamera_still.cpp
core/libcamera_app.cpp
core/libcamera_app.hpp
image/dng.cpp
image/image.hpp
image/jpeg.cpp
post_processing_stages/hdr_stage.cpp

It seems to be more in the spirit of the Exif and DNG specs to record the camera's "model" string, rather than its ID (which is neither a model nor a unique serial number), and to prefix a "Make" onto UniqueCameraModel.
The Make ("Raspberry Pi") is now a `#define` so that it can be overridden by Makefiles, but I'm happy to rework this.
Before:
```
Make                            : Raspberry Pi
Camera Model Name               : /base/soc/i2c0mux/i2c@1/imx708@1a
Unique Camera Model             : /base/soc/i2c0mux/i2c@1/imx708@1a
```
After:
```
Make                            : Raspberry Pi
Camera Model Name               : imx708_wide
Unique Camera Model             : Raspberry Pi imx708_wide
```
Here are some possible reasons why we might _not_ want this change:
- It changes behaviour that …

image: Exif "Model" tags should store camera model, not ID

---

preview/qt_preview.cpp

Implement luma offset for limited-range colourspaces (it makes a just-visible difference to black level in "libcamera-vid"). Claw back the increased complexity with some minor optimizations.
Rather than fix the (previously unintended?) U,V offset sharing, it has been made blatant to avoid further slowdown.

preview: QtPreview: Fix black level; optimize and tidy.

---

encoder/h264_encoder.cpp

Without this change, `libcamera-vid -t 0 --framerate 0` would typically lock up after a few hundred frames.
Also, I've increased the denominator to 90kHz so that rates such as 30fps, 29.97fps can be represented accurately.

encoder: H264: Trap framerate=0 to avoid division by zero error

---

image/yuv.cpp

The success path through yuv420_save does not close the file.  Fix this.

image: Fix missing fclose

---

utils/timestamp.py

Use ffprobe to read video timestamp information from mkv/mp4/avi
container files.
Slight formatting update to the output.

utils: Update the timestamp script to work with container files

---

core/libcamera_encoder.hpp

Need a missing #pragma once in this header file.

core: Add header guard in libcamera_encoder.hpp

---

preview/qt_preview.cpp

This simple change reduces viewfinder CPU-per-frame by a factor of at least 2 (tested on both ARM32 and ARM64).
Though where preview rate was limited by CPU it might not actually reduce total cycles (but might improve frame rate).
This reduces the benefit of the previous "U,V sharing" optimization, but the latter has been retained, to reduce code churn.
Further optimizations such as vectorizing the YUV->RGB conversion in signed 16-bit (rather than float) would yield diminishing returns and are not planned. If we really wanted further speedup we should arrange for a correctly-sized RGB888 source image!

preview: QtPreview: Copy source to a temporary line buffer for speed

---

core/options.cpp

Currently the LIBCAMERA_RPI_TUNING_FILE is set after the --list-cameras
option handling.  This causes the camera to not enumerate if a standard
tuning file is unavailable, and --list-cameras does not list it.
Move setting LIBCAMERA_RPI_TUNING_FILE to earlier in the options handler
function to fix this.

options: Set the custom tuning file as early as possible

---

image/dng.cpp

This code assumes that SRGGB16 etc are stored in memory in _native_ byte order (which is what TIFFWriteScanLine expects), therefore the "conversion" from 16 to 16 bits can just be a memcpy.

image: dng: Add support for 16-bit Bayer formats

---

core/video_options.hpp
encoder/libav_encoder.cpp

When recording audio using ALSA from a mono mic (attached to an USB
soundcard in my case), you get an error message like this:
_[alsa @ 0x5555638680] cannot set channel count to 2 (Invalid argument)_
When using Pulse, it works, but it's a waste of space on your microSD,
USB stick, USB HDD/SDD, network drive or whatever.
This commit implements an option that has the same effect as ffmpeg's
-ac option.

Add option --audio-channels.

---

.github/workflows/libcamera-test.yml
core/libcamera_app.cpp
core/libcamera_app.hpp
core/options.cpp

Move the camera listing functionality into a single static function. Sort the camera list vector so that the camera numbers presented to the user are always consistent, regardless of the device enumeration order in the kernel.

core: options: Sort cameras for consistency

---

output/file_output.cpp

Flush the file output before closing if the --flush flag is set.

output: Ensure we flush before closing a file

---

utils/test.py

The check_jpeg_shutter test would fail on the imx708 as the minimum gain is 1.12.  Update the test to use a gain of 2x to get around this.

tests: Update shutter test to use 2x gain

---

core/libcamera_app.cpp
core/libcamera_app.hpp
core/options.cpp

one way to fix issue https://github.com/raspberrypi/libcamera-apps/issues/527

core: adding method to access CameraManager

---

apps/libcamera_vid.cpp
core/libcamera_encoder.hpp
encoder/encoder.hpp
encoder/libav_encoder.cpp
encoder/libav_encoder.hpp

For review - DO NOT MERGE YET
@davidplowman @naushir @njhollinghurst
Have added the code to segment, pause, pause & split. Also updated codestyle

Segment and pause

---

core/video_options.hpp
encoder/libav_encoder.cpp
encoder/libav_encoder.hpp
output/file_output.cpp

Reprogrammed the implementation of segment, split and pause for when encoding with LibAV. Moved functionality to the encode thread New version should make it easier to implement timestamping and metadata for files.

encoder: New LibAV segment, split and pause implementation

---

core/video_options.hpp
encoder/libav_encoder.cpp

Set a default output file to /dev/null if none has been provided. Set the default container to an elementary stream.

libav: Allow libcamera-vid to run with minimal options using libav

---

core/video_options.hpp

this fixes libcamera-vid app when libcamera-apps is built with enable_libav=false option specified
previously the libcamera-vid app exited with the error `Invalid time string provided` no matter what parameters were passed, because the parameter parser was trying to decode parameters that are not present with the `enable_libav=false` build option set

libav: Fix parser with builds where enable_libav=false

---

core/libcamera_app.cpp
core/libcamera_app.hpp
core/options.cpp
core/options.hpp
image/dng.cpp

This commit adds support for the new SensorConfiguration within libcamera's CameraConfiguration object. We have to use this now to force the choice of particular sensor modes in case of future extensions where the raw stream format is no longer sufficient.
There are quite a few changes:
1. We now populate the list of sensor modes always, even when no framerate was given. Though we don't fill in the mode's framerate unless that's going to be something we use to select the mode.
2. The selectModeForFramerate function has been generalised and turned into selectMode. This now supports mode selection based on width, height, bitrate as well as (optionally) framerate.
3. Raw streams are always requested now, as this means we always get the same buffer management behaviour. It also simplifies the …

Support libcamera's new SensorConfiguration

---

core/libcamera_app.cpp
encoder/encoder.cpp

Update and rename check_camera_stack() to get_platform().  This functions now returns the running platform if known. The pipeline config files are now selected based on the detected platform.
As a drive-by add a missing close(fd) when detecting if the HW encoder is present.

core: Use correct pipeline config file for different platforms

---

core/libcamera_app.cpp

There may be other devices pluggin in so /dev/video0 may not reveal the platform correctly. Instead, try the first few /dev/video<n> nodes.

Check several /dev/video nodes in order to find the platform

---

core/libcamera_app.cpp

Preserve the historical behaviour where if a camera dev node is missing, we report it as "no camera available" instead of an unknown platform.

core: Better handling of missing camera dev nodes

---

core/libcamera_app.cpp
core/options.cpp
core/options.hpp

Update the --hdr option to support the single exposure multi-frame HDR mode available on the PiSP HW. The option can now take the following values:
"off": No HDR
"auto": Automically select the HDR mode, where "sensor" is top priority
"sensor": Sensor HDR (e.g. Camera v3)
"single-exp": Single exposure HDR mode
The implicit value of this argument is "auto".

core: Add single exposure PiSP HDR mode

---

preview/drm_preview.cpp

In DrmPreview::findCrtc() a series of drmModeGet*() functions is used. Those functions actually allocate memory that needs to be released with the corresponding drmModeFree*() call. In some cases resources are not freed causing a memory leak which can be confirmed with Valgrind.
Free all the allocated resources before losing the pointer.
Also fix a clear typo.

drm_preview: fix unreleased resources and a typo

---

core/options.cpp

With the recent HDR setup change, we open the camera manager much earlier, and before the LIBCAMERA_RPI_TUNING_FILE variable could be set. Fix this by setting the env variable before opening the camera manager.

options: Set the tuning file env variable before opening the camera

---

apps/rpicam_still.cpp
utils/test.py

This feature was broken when adding the zsl option, fix it. Add a regression test for the immediate option as well.

rpicam_still: Fix immediate capture breakage

---

core/video_options.hpp
encoder/libav_encoder.cpp
utils/test.py

This feature allows for specifying libav codec options.
AV1 encoding example with maximum encoding speed and low_latency on:
```
libcamera-vid -t 10000 --width 1280 --height 720 --framerate 30 --codec libav --libav-video-codec librav1e --libav-video-codec-opts "speed=10;rav1e-params=low_latency=true" -o video.webm
```
HEVC encoding example with ultrafast preset and main profile:
```
libcamera-vid -t 10000 --width 1280 --height 720 --framerate 30 --codec libav --libav-video-codec libx265 --libav-video-codec-opts "profile=main;preset=ultrafast" -o video.ts
```
H264 encoding example with the ultrafast preset, high profile and level 4.2:
```
libcamera-vid -t 10000 --width 1280 --height 720 --framerate 30 --codec libav --libav-video-codec libx264 --libav-video-codec-opts …
```

libav codec options

---

encoder/libav_encoder.cpp
encoder/libav_encoder.hpp

Some codecs do not seem to expose the profile array through AVCodec::profiles. Use the AVCodecDescriptor instead which seems to always be correct.

libav_encoder: Fix missing codec profiles for some codecs

---

apps/rpicam_detect.cpp

rpicam-detect fails to build.
The app parameter should be passed by reference.

Pass app to BufferReadSync by reference

---

core/options.cpp

We were only testing the "imx708" string and ignoring variant suffixes. Fix this by only searching for "imx708" as a substring.

options: Test all variants of IMX708 for HDR mode

---

apps/rpicam_vid.cpp

SIGPIPE gets raised when trying to write to an already closed socket. This can happen, when you're using TCP to stream to VLC and the user presses the stop button in VLC. Catching the signal to be able to react on it, otherwise the app terminates.

rpicam_vid: handling SIGPIPE to avoid sporadic app termination

---

.github/workflows/rpicam-apps-style-checker.yml
.github/workflows/rpicam-apps-test.yml
.github/workflows/rpicam-test.yml

The existing scripts use Node.js 16 which is deprecated.

actions: Update workflow scripts to Node.js 20

---

.github/workflows/rpicam-apps-style-checker.yml
.github/workflows/rpicam-apps-test.yml
.github/workflows/rpicam-test.yml
apps/rpicam_still.cpp
core/rpicam_app.cpp
core/rpicam_app.hpp
core/still_options.hpp
image/yuv.cpp
utils/test.py

Add support for 48-bpp RGB/BGR formats that can be generated by the PiSP.  rpicam-still can select this with the "--encoding rgb48" command line option.

rpicam_still: Add RGB/BGR 48bpp support

---

encoder/libav_encoder.cpp

The circular, segment, save_pts and split functions don't work when using the libav encoder.  Loudly warn if the user tries to use one of these options.

libav: Warn on using options that don't work with the libav encoder

---

encoder/encoder.cpp

VIDIOC_QUARYCAP is an unsigned long and should be passed as one.
Get rid of the following error:
encoder/encoder.cpp:32:37: error: overflow in conversion from 'long unsigned int' to 'int' changes value from '2154321408' to '-2140645888' [-Werror=overflow]
32 |                 int ret = ioctl(fd, VIDIOC_QUERYCAP, &caps);

encoder: pass VIDIOC_QUERYCAP as unsigned long

---

core/options.cpp
core/options.hpp
core/rpicam_app.cpp
encoder/encoder.cpp
output/output.cpp

Add a helper to get the platform identifier to the options class. This is the most convenient place for the helper as all rpicam-apps components get the options pass into it.

options: Add GetPlatform() helper

---

apps/rpicam_still.cpp
core/frame_info.hpp
core/rpicam_app.cpp
post_processing_stages/annotate_cv_stage.cpp

This allows the constructor to set fps and sequence directly rather than having to do it outside of the class. Fixes the annotate stage where we don't set the fps field.

core: Use CompletedRequestPtr in the FrameInfo constructor

---

image/dng.cpp

These have changed from XXXX16_PISP_COMP1 to XXXX_PISP_COMP1.

dng: Update libcamera format strings for PISP formats

---

core/options.cpp

Do not set HDR control switch on all IMX708 subdev nodes available. Rather, traverse through sysfs and find the correct subdev node to toggle the HDR control on and off. We aim to match the selected camera device id when deciding which subdev node to use.

core: Better handling of IMX708 sensor HDR

---

core/options.cpp
core/options.hpp
core/post_processor.cpp
core/rpicam_app.cpp
post_processing_stages/hailo/hailo_postprocessing_stage.cpp
post_processing_stages/hailo/hailo_postprocessing_stage.hpp
post_processing_stages/hailo/hailo_yolo_inference.cpp
post_processing_stages/hailo/hailo_yolov8_pose.cpp

Add a HailoPostProcessingStage::ConvertInferenceCoordinates() helper that converts from the inference (low res) image co-ordinate space to the main image space, accounting for different scaler crops.
Fixup the Yolo inference and pose estimation stages to use this new helper.

postprocess: hailo: Handle multiple scaler crops on the ISP outputs

---

.github/workflows/gen_orig.yml

The previous version treats `build/meson-dist/*.tar.xz hailo-models-*.tar.xz` as a single file, which it fails to find.

gen_orig.yml: fix workflow

---

post_processing_stages/hailo/hailo_postprocessing_stage.cpp
post_processing_stages/hailo/hailo_postprocessing_stage.hpp

The vdevice is a singelton and multiple Hailo postprocessing stages must use the same vdevice instance in order to acquire the hardware.

postprocessing: hailo: Add singeton for vdevice

---

post_processing_stages/meson.build

The include paths for the postprocessing so files were wrong, fix it.

postprocess: build: Correct include paths

---

core/rpicam_app.cpp
utils/test.py

The controls::rpi::ScalerCrops is only relevant to PiSP platforms in the upstream libcamera code.
Also while at it, add a test for crops.

core: Use controls::ScalerCrop on VC4 platforms

---

core/video_options.hpp
encoder/libav_encoder.cpp

Add a new command line argument (--low-latency) to the video options allowing users to switch on encoder tuning parameters for low latency video encode. Note that this mode will turn down the encoder efficiency by disabling more advanced features, e.g. B-frames.

libav: Add a low latency encode option

---

.gitignore
apps/rpicam_vid.cpp
core/rpicam_encoder.hpp
core/video_options.hpp

A "sync" option has been added, which may take the values "server" or "client", turning the camera into either the server of client of a synchronised recording.
Recording only starts once the sync algorithm flag that the cameras are "ready to go".

rpicam-vid: Update for camera sync algorithm

---

apps/rpicam_raw.cpp
apps/rpicam_vid.cpp
core/rpicam_encoder.hpp
encoder/libav_encoder.cpp
encoder/libav_encoder.hpp

Two changes here:
When using sync mode, only start the timer (or frame counter) when the sychronisation point is reached. This fixes the previously stupid behaviour where the time spent waiting for sync was being included. (Documentation PR will need another update!)
Secondly, fix a crash when using Ctrl-C to quit _before_ the synchronisation point has occurred.
@naushir Could you take a look and merge if happy? Thanks!

Sync fixes

---

core/rpicam_app.cpp

This matches the behaviour of Picamera2.

core: Set the lores colourspace to match the main stream colourspace.

---

core/rpicam_app.cpp
core/rpicam_app.hpp

If camera_manager_ has not been initialised, do it before returning the pointer to the caller.

core: Initialise the camera manager from GetCameraManager() if needed

---

encoder/libav_encoder.cpp

This ensures the user knows there is an error (and why) rather than missing the log message.
Also add the "pause" option to the incompatible list.

libav: Make incompatible options fatal

---

core/rpicam_encoder.hpp
core/video_options.hpp

Based on the original commit that added the sync feature there were a few more options that needed the disable_rpi_features code conditionals to ensure compilation against upstream libcamera so add them in to ensure this works.
Fixes: c529096 ("core: Add "disable_rpi_features" meson option")

core: Update checks for disable_rpi_features option

---

assets/hailo_yolov5_segmentation.json
post_processing_stages/hailo/hailo_yolov5_segmentation.cpp
post_processing_stages/hailo/meson.build

Switch back to Yolov5 segmentation model.
Allow empty hailort pp file.
Copy the yolov5 pp file to the assets dir.

postproc: hailo: Fix for segmentation demo

---

encoder/libav_encoder.cpp
encoder/libav_encoder.hpp
output/output.cpp

If we are encoding an elementary stream, allow the libav encoder to use the Output class for file generation. This will enable features such as split, segment, and pause through the libav encoder for a constrained set of cases.

libav: Allow restricted use of the Output class with libav_encoder

---

core/rpicam_app.cpp

This was missing from the list. Ensure we handle both "packed" and "unpacked" formats - they are the same for 16-bit modes.

core: Add 16-bit modes to the mode_to_pixel_format() helper

---

post_processing_stages/object_detect_udp_stage.cpp

gcc 14 was throwing false positives about possible buffer overflows when populating the udp_data_buffer.  Fix this by refactoring the code to be more explicit with the memcpy.
Also fix some styling issues with the source file.

postprocess: object_detect_udp: Fix compiler warnings and styling

---

post_processing_stages/segmentation.hpp

When compiling with gcc15, compiliation fails with the following error:
```
| In file included from ../sources/libcamera-apps-1.9.0/post_processing_stages/segmentation_tf_stage.cpp:8: | ../sources/libcamera-apps-1.9.0/post_processing_stages/segmentation.hpp:15:82: error: 'uint8_t' was not declared in this scope
|    15 |         Segmentation(int w, int h, std::vector<std::string> l, const std::vector<uint8_t> &s)
```
To avoid it, add the cstdint header to the offending file.

add missing header
