test.py

We perform a very simple check that the file exists, that the header
is as we expect, and that the first two entries are numeric and
increasing.

Add a test to check timestamp files written by libcamera-vid

---

core/options.hpp

- Allow options to be read from a config file.
- Improve readability of the options help text.

Various changes to the options parsing

---

core/libcamera_app.cpp
core/libcamera_encoder.hpp

Two small tweaks are required:
- in libcamera_app.cpp we must spot planes with the same fd and
accumulate them so as to mmap the buffer as a single plane
- in libcamera_encoder.hpp we must be careful to pass the full buffer
size to the encoder not the plane's length (which is now just the Y
portion)

Cope with libcamera now returning single plane buffers as if multi plane

---

output/net_output.cpp

We can't send arbitrarily large UDP packets, they have to be broken
up. I've gone with 65507 which is the largest sendto will accept, in
theory the network stack will fragment it further if it needs to.

output: Fix sending of large UDP packets

---

core/CMakeLists.txt
encoder/CMakeLists.txt
image/CMakeLists.txt
output/CMakeLists.txt
post_processing_stages/CMakeLists.txt
preview/CMakeLists.txt

Signed-off-by: Damian Wrobel <dwrobel@ertelnet.rybnik.pl>

Install libraries as per GNU Coding Standards

---

core/CMakeLists.txt
core/options.hpp
core/version.cmake
core/version.cpp.in
core/version.hpp
core/version.py
preview/drm_preview.cpp
preview/egl_preview.cpp
preview/null_preview.cpp
preview/preview.cpp
preview/preview.hpp
preview/qt_preview.cpp

@davidplowman, might be worth giving this a go on your environment to make sure it works correctly!

Version information for libcamera-apps

---

test.py

tests: Further adjustments to timeouts.

---

core/version.py

Update to version script.

---

.github/workflows/libcamera-apps-test.yml

actions: Run a clang build as part of the tests.

---

.github/workflows/libcamera-apps-test.yml

actions: Add imx477 run test.

---

image/bmp.cpp
image/jpeg.cpp
image/png.cpp

image: Support writing still images to stdout

---

core/options.cpp

build: fix clang 11 compiler error

---

core/libcamera_app.cpp

If we definitely are, give up. Anything else - even if not a Pi at all
- we let through.

core: Check we are not running the legacy camera stack

---

utils/timestamp.py

utils: Add timestamp analysis tool.

---

core/libcamera_app.cpp

We do this by always requesting a raw stream even though we may not
otherwise use it. This defaults to full resolution, thereby forcing
the selection of that camera mode.
It can be overridden with the --mode option, if desired.

core: Force still capture to default to full resolution camera mode

---

core/options.cpp

This change pulls out a list of sensor modes through generateConfiguration()
with a RAW streamrole and displays it when the --list-cameras options is
invoked.

options: Display supported sensor modes with --list-cameras option

---

apps/libcamera_vid.cpp
core/libcamera_app.cpp
core/libcamera_app.hpp
core/stream_info.hpp
encoder/h264_encoder.cpp
preview/drm_preview.cpp
preview/egl_preview.cpp
preview/qt_preview.cpp

Colour spaces

---

preview/preview.cpp
utils/camera-bug-report

1) Fix for camera-bug-tool invalid utf-8 conversion.
2) Display preview mode on startup.

Couple of changes

---

apps/libcamera_still.cpp

When the timelapse interval is very short you can get back-to-back
captures with no preview frames actually being processed. This changes
forces just a few preview frames to be delivered, allowing for better
AGC/AWB adjustment when conditions are changing.

libcamera-still: Force a few preview frames between timelapse captures

---

core/libcamera_app.cpp
core/options.cpp

Do not advertise USB webcams, they are not supported in libcamera-apps.

---

core/video_options.hpp

libav: Update the audio-codec command line option to be consistent.

---

core/libcamera_app.cpp

It might be useful for the user to know the sensor control limits.

core: Display available controls with the verbose flag.

---

core/frame_info.hpp
core/libcamera_app.cpp
core/libcamera_encoder.hpp
core/options.cpp
image/dng.cpp
image/jpeg.cpp
utils/test.py

This now returns a std::optional<T> type to avoid double lookups.

core: Update new API usage for libcamera::controls::get()

---

core/options.cpp

options: Use std::cout for --help, --list-cameras and --version output

---

core/libcamera_app.cpp
preview/drm_preview.cpp
preview/egl_preview.cpp
preview/qt_preview.cpp

s/libcamera::ColorSpace::Jpeg/libcamera::ColorSpace::Sycc/

Fix for libcamera libcamera::ColorSpace::Jpeg API change

---

core/libcamera_app.cpp
core/libcamera_app.hpp
core/options.cpp
core/options.hpp
encoder/h264_encoder.cpp
encoder/libav_encoder.cpp

- options: Switch to std::optional for framerate
- core: Use automatic mode selection for framerate

Mode selection for framerate

---

core/frame_info.hpp
core/options.hpp

core: Add autofocus status reporting in FrameInfo

---

README.md

Update the URL in README.md to point to the updated documentation page.

core: Update documentation URL

---

core/options.cpp
core/options.hpp

core: Add HDR option, with a stop-gap implementation using V4L2 control

---

apps/libcamera_detect.cpp

Added --datetime --timestamp and --timeformat options for using the current date and time to construct the output file name.

libcamera-detect: Add multiple file name output generation options

---

core/libcamera_app.cpp

We already have a refence to `stream->configuration()`. I think we can use it
https://github.com/raspberrypi/libcamera-apps/blob/40e001251d04a7e416ecfcfd883e48016c39e912/core/libcamera_app.cpp#L778

core: minor code refactoring

---

core/libcamera_app.cpp

If the LIBCAMERA_RPI_CONFIG_FILE environment variable is set then we respect it, otherwise we point it at the /usr/local/share or /usr/share version of rpi_apps.yaml, whichever we find first.

Set the pipeline configuration file

---

.github/workflows/libcamera-apps-test.yml
.github/workflows/libcamera-test.yml

Update the actions to the new meson build system

actions: Update to meson build system

---

core/video_options.hpp
encoder/h264_encoder.cpp
encoder/libav_encoder.cpp
meson.build

Also a small commit to fix x64 builds with OpenCV.

Changes for bitrate units.

---

core/libcamera_app.cpp
core/options.cpp
core/options.hpp

Allow user to set the flicker period through the --flicker-period command line argument.

core: Add flicker correction control

---

utils/timestamp.py

Not all containers use "pts_time" as a timestamp key.  Add the ability to read one of multiple timestamp keys to use instead.

utils: timestamp: Check multiple timestamp keys in container files

---

.github/workflows/rpicam-apps-test.yml
.github/workflows/rpicam-test.yml

This will be used by other repo tests, so move it to /home/pi/libcamera_lkg.

actions: Move libcamera_lkg dir

---

apps/rpicam_still.cpp

This is a more robust way of creating the latest file symlink, and allows the symlink to be created in a directory different to the output files.

rpicam_still: Use std::filesystem to create latest symlink

---

.github/workflows/gen_orig.yml

Use Debian packaging tarball names
Update to action-gh-release v2
Generate IMX500 models tarball
Check that project and tag versions match

Update gen_orig.yml workflow

---

core/meson.build
core/options.cpp
core/version.cpp.in
core/version.hpp
meson.build
post_processing_stages/hailo/meson.build
utils/version.py

This will be printed out with the --version command line argument.

core: build: Add capabilities string to the version information.
